version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  versioning-strategy: increase
  ignore:
  - dependency-name: ts-loader
    versions:
    - 8.0.18
    - 8.1.0
    - 9.0.0
    - 9.0.2
    - 9.1.0
  - dependency-name: "@types/jasmine"
    versions:
    - 3.6.4
    - 3.6.6
    - 3.6.7
    - 3.6.8
    - 3.6.9
  - dependency-name: "@types/node"
    versions:
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: karma
    versions:
    - 6.1.1
    - 6.1.2
    - 6.2.0
    - 6.3.0
    - 6.3.1
  - dependency-name: jasmine-core
    versions:
    - 3.7.0
  - dependency-name: typescript
    versions:
    - 4.2.3
  - dependency-name: music-metadata-browser
    versions:
    - 2.2.5
  - dependency-name: node-fetch
    versions:
    - 2.6.1
- package-ecosystem: npm
  directory: "/node"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  versioning-strategy: increase
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.24
    - 14.14.28
    - 14.14.30
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.37
    - 14.14.39
    - 15.0.0
  - dependency-name: "@types/chai"
    versions:
    - 4.2.16
  - dependency-name: music-metadata
    versions:
    - 7.6.5
    - 7.6.8
    - 7.8.0
    - 7.8.3
    - 7.8.4
  - dependency-name: mocha
    versions:
    - 8.3.1
  - dependency-name: typescript
    versions:
    - 4.1.5
    - 4.2.3
  - dependency-name: "@types/mocha"
    versions:
    - 8.2.1
